### ISSUE TITLE
Em qual sistema essa lib foi usada? Por um acaso algum de controle de empréstimo em biblioteca?

### ISSUE THREAD

**Issue by thiagogomesverissimo** [uspdev/cutter#2]

**Comment by masakik** [comment]
Ainda não foi usado mas a proxima etapa é mexer no formulário de ficha catalográfica nossa que é feito manualmente a inserção desse código. Aliás eu não vi alguém que tenha esse código automatizado como essa biblioteca faz.

**Comment by masakik** [comment]
Aliás alguém gostaria de montar um projeto aqui no uspdev para geração de ficha catalográfica?

**Comment by masakik** [comment]
Não sei se o controle de empréstimo utilizaria um sistema desses. Seria utilizado na geração da lombada do livro por exemplo mas não no processo de empréstimo. Me corrijam se eu estiver errado.
